In [1]:
import numpy as np

In [4]:
a = np.ones((3,3))
print(a)

b = np.full((3,3),5)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


array([[15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.]])

In [5]:
np.linalg.det(a)

0.0