<a href="https://colab.research.google.com/github/ukashasohail/regex-python/blob/master/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [4]:
# creating a np array
my_array = np.array([[6,5,6],[5,8,7]])
print(my_array)

[[6 5 6]
 [5 8 7]]


In [6]:
# np array properties
print(my_array.ndim)
print(my_array.shape)
print(my_array.dtype)
print(my_array.itemsize)
print(my_array.nbytes)


2
(2, 3)
int64
8
48


In [8]:
# accessing elements in np array
array_1 = np.array([[2,6,9,7,5,6,0,5],[2,6,96,4,5,3,7,8]])
print(array_1)''

[[ 2  6  9  7  5  6  0  5]
 [ 2  6 96  4  5  3  7  8]]


In [9]:
# access a certain elements
element0 = array_1[0,5]
print(element0)

6


In [11]:
# access a entire row
row0 = array_1[0,:]
print(row0)

# access an entire column
column0 = array_1[:, 1]
print(column0)

[2 6 9 7 5 6 0 5]
[6 6]


In [14]:
# slicing np array
slice0 = array_1[:, 2:5]
print(slice0)

[[ 9  7  5]
 [96  4  5]]


In [15]:
# mutating elements of np array
array_1[1,5] = 100
print(array_1)

[[  2   6   9   7   5   6   0   5]
 [  2   6  96   4   5 100   7   8]]
